import Head from 'next/head';
import '@/styles/globals.css';
import FloatingButtons from '@/components/floatingButtons';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import { ReCaptchaProvider } from 'next-recaptcha-v3';
import configs from '@/configs/configs';

export default function App({ Component, pageProps }) {
  const router = useRouter();
  const [url, setUrl] = useState('');

  useEffect(() => {
    let pathname = router.pathname.split('/')[1];
    setUrl(pathname);
  }, [router.isReady])

  return (
    <ReCaptchaProvider reCaptchaKey={configs.recaptcha_sitekey}
      scriptProps={{
        async: true,
        defer: false,
        appendTo: "head",
        nonce: undefined
      }}
    >
      <Head>
        <title>Blink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      {
        url !== 'auth' && <FloatingButtons />
      }

    </ReCaptchaProvider>

  );

}
